apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-rbac-proxy
  namespace: kube-rbac-proxy-simple
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-rbac-proxy
  namespace: kube-rbac-proxy-simple
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: kube-rbac-proxy
    namespace: kube-rbac-proxy-simple
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-rbac-proxy
  name: kube-rbac-proxy
  namespace: kube-rbac-proxy-simple
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app: kube-rbac-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rbac-proxy
  namespace: kube-rbac-proxy-simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rbac-proxy
  namespace: kube-rbac-proxy-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rbac-proxy
  template:
    metadata:
      labels:
        app: kube-rbac-proxy
    spec:
      serviceAccountName: kube-rbac-proxy
      containers:
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:local
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8081/"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 9090
              name: dlv
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
        - name: echo-server
          image: mendhak/http-https-echo
          env:
            - name: HTTP_PORT
              value: "8081"
            - name: HTTPS_PORT
              value: "9443"
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 9443
              name: https